# SPDX-FileCopyrightText:  gb-open-market-model contributors
#
# SPDX-License-Identifier: CC0-1.0

name: Update pinned envs on GB project
on:
  push:
    paths:
    - envs/**/*.yaml
    - .github/workflows/update-gb-model-pinned-env.yaml
  schedule:
  - cron: "0 8 1,16 * *" # Bi-weekly

jobs:
  update-locked-environment:
    name: Update pinned envs on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    if: ${{ github.ref == 'refs/heads/master' }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v5

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        activate-environment: ${{ github.event.repository.name }}

    - name: Install snakedeploy
      run: |
        conda install bioconda::snakedeploy

    - name: Generate lockfiles for current platform
      run: |
        find envs -name "*.pin.txt" -exec rm {} \;
        find envs -name '*[!lock].yaml' -exec snakedeploy pin-conda-envs {} \;

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        # all are uploaded to the same artifact as they will have different names for each platform so won't clash.
        name: lockfiles-${{ matrix.os }}
        path: envs/**/*.pin.txt

  create-pull-request:
    permissions:
      contents: write
      pull-requests: write
    needs: update-locked-environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Download all artifacts
      uses: actions/download-artifact@v5
      with:
        pattern: lockfiles-*
        path: envs/
        merge-multiple: true

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: update-pinned-environment
        title: "[github-actions.ci] Update pinned envs"
        body: |
          Automatically generated PR to update pinned environment files for Windows, macOS, and Linux.

          These files were generated using snakedeploy for improved dependency resolution and reproducibility.

          **Note: Do not merge without manual test execution. Either update the branch to trigger tests, or use `workflow_dispatch` to run tests manually. Unlike standard PRs, tests will not run automatically.**
        commit-message: "Update pinned environment files for all platforms"
